### ISSUE TITLE
Errors on login after prepatch

### ISSUE THREAD

**Issue by TheNeutrinoRaged** [EthanCentaurai/Chinchilla#10]
Hi I'm using version v2.8.6-7-gaa2ed6f-alpha and I'm getting the following 3 errors on login:
https://www.wowace.com/paste/45821237
https://www.wowace.com/paste/26c8cb7
https://www.wowace.com/paste/1b93265b5

And when I click on the Show/Hide module settings, there is just a blank pane like this:
![image](https://user-images.githubusercontent.com/26345725/43010973-e9997674-8c39-11e8-858c-f96a4eb78d8a.png)

I can see  AceAddon-3.0 mentioned a lot in the error messages so I don't know if there even is a problem with chinchilla, but I thought I'd post the errors here anyway

**Comment by EthanCentaurai** [comment]
Hello,

You are using an out of date version. The error in your paste was fixed in v2.8.6-2. Please download and install the latest alpha package and let me know if anything happens.

**Comment by TheNeutrinoRaged** [comment]
D'oh! thanks for the response I'll update now
