### ISSUE TITLE
Error from v2.9-beta1

### ISSUE THREAD

**Issue by aphathead** [EthanCentaurai/Chinchilla#12]
Just a quick error report I recieved after installing the beta release. 
Let me know if you need anything else. Thanks!!

Date: 2018-07-22 14:52:33
ID: 2
Error occured in: Global
Count: 1
Message: Usage: local position = C_Map.GetPlayerMapPosition(uiMapID, unitToken)
Debug:
   [C]: ?
   [C]: ?
   Chinchilla\Modules\Coordinates.lua:70: func()
   ...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:57:
      ...rkInventory\Externals\Ace3\AceTimer\AceTimer-3.0.lua:50
Locals:

AddOns:
  Swatter, v5.0.0 (<%codename%>)
  ArkInventory, v30804
  ArkInventoryRules, v10200
  ArkInventorySearch, v10200
  AskMrRobot, v61
  Auctionator, v5.0.4
  Bartender4, v4.8.1
  BrokerDurabilityInfo, vv1.28
  BrokerProfessionsMenu, v8.0.0.2
  BrokerXPRate, v1.67
  Chinchilla, vv2.9-beta1
  ChocolateBar, vv3.1.8
  Clique, vv80000-1.0.0
  DBMCore, v@project-version@
  DBMDefaultSkin, v
  DBMStatusBarTimers, v
  Decursive, v2.7.6
  ExRT, v3930
  FixRaidTaint, v0.2
  HandyNotes, vv1.5.2
  HandyNotesDraenorTreasures, v1.21
  HandyNotesKosumoth, v1
  HandyNotesLegionTreasures, v1
  iGuild, v7.3.0
  LDBFriends, v1.05a
  MikScrollingBattleText, v5.7.149
  NomiCakes, v8.0.0.1
  OmniCC, v8.0.0
  QuickMark, v
  Skada, v1.7.3
  SlideBar, v5.0.0 (<%codename%>)
  TidyPlatesThreatPlates, v9.0.5
  TidyThreat, v2.8
  ZPerl, v5.5.7
  ZPerlArcaneBar, v
  ZPerlOptions, v
  ZPerlPlayer, v
  ZPerlPlayerPet, v
  ZPerlTarget, v
  ZPerlTargetTarget, v
  BlizRuntimeLib_enUS v8.0.1.80000 <none>
  (ck=3d5)

**Comment by wowcamo** [comment]
It seems to have fixed it for druids, cause it didn't happen on druid when hearthing to homebase, but it still happened to monk, seems like the maps for classes with out of the normal map will spit out the error.
