### ISSUE TITLE
Nandini and Nandini New Tracking Dots.

### ISSUE THREAD

**Issue by l3uGsY** [EthanCentaurai/Chinchilla#14]
Thanks for the quick fix Ethan.  I did notice one error, NPC and Players are incorrect and have swapped places for Nandini and Nandini New.  

I did comment on the old ticket hoping it would reopen but it didn't so I delete and made a new one.

**Comment by l3uGsY** [comment]
Oh and I just noticed, the same applies to Enemy Player and Enemy NPC

**Comment by EthanCentaurai** [comment]
Should be good now. Thanks :smile: 
Let me know if I've messed up the others. I probably did... :thinking:
