### ISSUE TITLE
v2.9-beta2-1 alpha Map is shifted

### ISSUE THREAD

**Issue by amiyuy** [EthanCentaurai/Chinchilla#18]
Down by ~40 pixels
Left by ~13 pixels

![2018-08-03_chinchillamove](https://user-images.githubusercontent.com/3958649/43657628-3b22e09e-970b-11e8-978e-5a559faa7021.jpg)

Settings
2.9-beta1: https://www.dropbox.com/s/ynsx5x46rn4tz74/Chinchilla-2_9-beta1.lua?dl=0
2.9-beta2-1_alpha: https://www.dropbox.com/s/apn013jgbfpsnqc/Chinchilla-2_9-beta2_alpha.lua?dl=0

If I downgrade back to 2.9-beta1 it goes back to the correct position.

**Comment by EthanCentaurai** [comment]
This is an unfortunate side effect from fixing #13 and #17. Move it back to where it was and it should stay put.

**Comment by amiyuy** [comment]
Oh, also the cardinal indicators are enabled, which you can see I did not have activated before.

**Comment by EthanCentaurai** [comment]
The indicators are from the Compass module that was reenabled shortly before beta2. I had disabled it in the past due to a bug and completely forgot about it. :sweat_smile: 

You can turn it off in the config if you don't like it.
