### ISSUE TITLE
Addon Action Blocked

### ISSUE THREAD

**Issue by Mardleseyth** [EthanCentaurai/Chinchilla#21]
1x [ADDON_ACTION_BLOCKED] AddOn 'Chinchilla' tried to call the protected function 'UNKNOWN()'.
!BugGrabber\BugGrabber.lua:519: in function <!BugGrabber\BugGrabber.lua:519>
[C]: ?
[C]: in function `Show'
FrameXML\ActionBarController.lua:165: in function `BeginActionBarTransition'
FrameXML\ActionBarController.lua:192: in function `ValidateActionBarTransition'
FrameXML\ActionBarController.lua:143: in function `ActionBarController_UpdateAll'
FrameXML\ActionBarController.lua:62: in function <FrameXML\ActionBarController.lua:51>

Locals:
InCombatSkipped

**Comment by EthanCentaurai** [comment]
Blizzard issue. Not Chinchilla.
