### ISSUE TITLE
8.1 broke tracking dots

### ISSUE THREAD

**Issue by zalidthebur** [EthanCentaurai/Chinchilla#27]
Only the "Blizzard" style works now. All the others give a weird icon that is not obvious to see. Guess Blizzard broke something with the patch.

**Comment by EthanCentaurai** [comment]
I think I did it. Please download v2.9.1-4-gc57d013-alpha from WoWace or the Twitch App and let me know.

**Comment by zalidthebur** [comment]
Looks good to me. Thanks for the quick response and fix ;-)
