### ISSUE TITLE
7.2.5 Icons wrong again

### ISSUE THREAD

**Issue by amiyuy** [EthanCentaurai/Chinchilla#3]
All styles except for Blizzard default are showing the wrong tracking icons.

Ex: Mailbox tracking is showing me the green flight point icon.

![2017-06-13_chinchillaicons](https://user-images.githubusercontent.com/3958649/27103460-8a510fa8-503d-11e7-9b38-9a289d0e8ee0.png)

**Comment by adrnde** [comment]
Confirm - looks like a new icon was added? A left-facing fat letter c.  Could you add a short guide on how icons for this addon work, and how to start or fix a set? I looked at fixing it myself, but exactly how icons are referenced isn't exactly clear to someone who hasn't written lua script before.

**Comment by EthanCentaurai** [comment]
Unfortunately there is no guide (that I know of anyway).

Some automated program/script adds new icons to the "atlas" in patches, which is essentially one large image file with all the icons inside.  When this happens, all of the icons get jostled about which is what causes this issue in Chinchilla.  This is why the "Default" blip set always works, but the other ones won't.

The only way to fix it is to update each individual custom blip "atlas" file inside Chinchilla to match the new layout. 

I'll try to get this fixed this evening.

**Comment by EthanCentaurai** [comment]
Should be fixed as of v2.8.4. Let me know if anything explodes. :+1:
