### ISSUE TITLE
Minimap Icons (Hi again!  :) )

### ISSUE THREAD

**Issue by l3uGsY** [EthanCentaurai/Chinchilla#30]
Looks like they did it again.  

 Blue exclamation is now a question mark and I imagine there are more.  :( 

Thanks again for all your work on this addon and continuing to keep it alive.  The only addon with Color Blind Blip support.    <3

**Comment by EthanCentaurai** [comment]
Should be good to go now. Please download v2.9.3 from CurseForge or the Twitch App and let me know if I've missed anything.
