### ISSUE TITLE
Hiding addon minimap buttons

### ISSUE THREAD

**Issue by lcatania** [EthanCentaurai/Chinchilla#33]
Hi is there a way to hide all minimap button? 
Iam trying to hide the buttons for my other addons.

Thanks for the answer :)

**Comment by lcatania** [comment]
Nevermind i figured out. I just disabled the minimap button in every single addon. my bad sorry

**Comment by EthanCentaurai** [comment]
No worries.  There is some very limited support for addons that use the LibDBIcon-1.0 library but I've left showing and hiding addon buttons out for now. Mostly to avoid conflicts, mostly because I don't know how to code it cleanly. 😛
