### ISSUE TITLE
Menu no longer loading via Mouse click.

### ISSUE THREAD

**Issue by KleaRusnim** [EthanCentaurai/Chinchilla#34]
Unable to load the settings menu via mouse click anymore since latest patch.

**Comment by EthanCentaurai** [comment]
It's working ok here on my end I'm afraid. You can type "/chin" in the chat to open it up that way. It may be that the setting was changed to a different button.

I should probably add that to the readme.  🤔

**Comment by EthanCentaurai** [comment]
It's been two months and I'm yet to receive a response about this, so I'm going to assume the chat command solved your problem.
