### ISSUE TITLE
Minimap Icons (the usual) :)

### ISSUE THREAD

**Issue by l3uGsY** [EthanCentaurai/Chinchilla#35]
Colorblind Icons for the minimap are out of whack again.  

As always, thank you so much for your continued work on this addon.

**Comment by EthanCentaurai** [comment]
Not again. 😛

I'll have to work on this later sadly. CurseForge has unveiled its "new and improved website" and broke everything in the process. I can upload the fixed versions here on GitHub but until CurseForge fixes their colossal screw-up it won't appear on the Twitch app.

**Comment by l3uGsY** [comment]
Would that be here?
https://github.com/EthanCentaurai/Chinchilla/releases

Or would it be somewhere else?

**Comment by EthanCentaurai** [comment]
It would have been [here](https://github.com/EthanCentaurai/Chinchilla) by clicking the green "Clone or Download" button.  It looks like CurseForge have fixed the issues now anyway so I'll work on fixing this over the weekend and everything *should* appear on CurseForge and the Twitch app as normal. 🤞

**Comment by malikoth** [comment]
The icons in the Nandini New set are mixed up as well. They appear to be working in the version downloaded from the link you shared above (2.9.5-beta2) but not yet on Twitch.
(I'm commenting for my wife who uses your addon)

**Comment by EthanCentaurai** [comment]
Aye, I think it's about time I moved v2.9.5 to the release channel. 🤔
