### ISSUE TITLE
2.9.5-beta1 icons not working

### ISSUE THREAD

**Issue by zalidthebur** [EthanCentaurai/Chinchilla#37]
Just tried the 2.9.5-beta1 and tested it.

I can confirm what aisenfaire said in comments, that "Big Blizzard" and "Blizzard, Big Resources" are not working.

Hope you can fix "Blizzard, Big Resources" as that is the one I use :-)

**Comment by EthanCentaurai** [comment]
They should be fixed in a newer alpha. I may have forgotten to tag a new beta... whoops. 😛

**Comment by zalidthebur** [comment]
Good to know. And LOL ;-)
