### ISSUE TITLE
minimap icons

### ISSUE THREAD

**Issue by amey1956** [EthanCentaurai/Chinchilla#4]
broke again - typical blizzard ;)

**Comment by EthanCentaurai** [comment]
Bah, not again! :anger:

I'll get this fixed at some point tomorrow after 7.3 goes live in EU.

**Comment by EthanCentaurai** [comment]
Should be all fixed in v2.8.5. Let me know if anything goes wrong.

**Comment by amey1956** [comment]
thanks ;)
